# This code comunicate with ec2 when the new code push to the github so that ec2 pull the latest code and install the dependencies

name: Deploy OG Mart

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd /home/ec2-user/Ecommerce-mart-

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            npm ci

            echo "Building application..."
            npm run build

            echo "Restarting OG Mart..."
            pm2 restart og-mart --update-env

            echo "Deployment completed!"